import Head from 'next/head'
import { ReactNode } from 'react';
import styles from './Layout.module.css'

export default function Home( { children }: { children: ReactNode } ) {
  return (
    <div className={styles.container}>
      <Head>
        <title>NeteaseCloudMusic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.head}>

      </header>
      <aside className={styles.leftSide}>

      </aside>
      <div className={styles.playBar}>

      </div>
      <main className={styles.main}>
        {children}
      </main>
    </div>
  )
}