import '../styles/globals.css'
import Head from 'next/head'
import styles from './style.module.css'

function MyApp({ Component, pageProps }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>NeteaseCloudMusic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.head}>

      </header>
      <aside className={styles.leftSide}>

      </aside>
      <div className={styles.playBar}>

      </div>
      <main className={styles.main}>
        <Component {...pageProps} />
      </main>
    </div>
  )
}

export default MyApp
