import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import Discovery from './discovery/index'
import { useEffect } from 'react';

export default function Home() {
  const router = useRouter();

  // useEffect(() => {
  //   router.push('/divcovery/recommendation');
  // }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>NeteaseCloudMusic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.head}>

      </header>
      <aside className={styles.leftSide}>

      </aside>
      <div className={styles.playBar}>

      </div>
      <main>
        <Discovery></Discovery>
      </main>
    </div>
  )
}
